### ISSUE TITLE
favicon not loading problem

### ISSUE THREAD

**Issue by peterennis** [ionic-team/tutorial-photo-gallery-vue#1]
@dotNetkow 

Working through the docs to build app.
I could not load my favicon - tried rebuild, prod build,
icon cache reset (WIndows), clear cache - but no luck.

Traced problem to manifest here:

![2020-10-03 18_12_17-Window](https://user-images.githubusercontent.com/140737/95004751-64de5580-05a4-11eb-9054-8882123278b2.png)

Finally did this:

![2020-10-03 18_16_47-Window](https://user-images.githubusercontent.com/140737/95004784-bf77b180-05a4-11eb-83ce-4b212947a0e0.png)

and get this result:

![2020-10-03 18_24_40-Window](https://user-images.githubusercontent.com/140737/95004873-ceab2f00-05a5-11eb-8c2e-fe684ea68c99.png)

I am not really sure if this is a bug or Windows/Mac difference.

I can make a PR if it is a bug.

**Comment by dotNetkow** [comment]
Good catch! I missed that. Please pull latest from main. I removed the slash.
