### ISSUE TITLE
Unable to take photo! DOMException: The associated Track is in an invalid state.

### ISSUE THREAD

**Issue by peterennis** [ionic-team/tutorial-photo-gallery-vue#10]
I also see a bunch of other errors:
`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined`

![2020-11-13 18_44_57-Window](https://user-images.githubusercontent.com/140737/99137586-be449600-25e0-11eb-86a4-3f5e0e5beb05.png)

**Comment by klrkt** [comment]
Feedback (based on my steps):
1. I used Windows 10, but could not follow the tutorial here:
	https://ionicframework.com/docs/vue/your-first-app
	My first problem started here:
	https://ionicframework.com/docs/vue/your-first-app/2-taking-photos
	I got a buch of wierd errors, I fixed by:
	Changing package.json from: "typescript": "~3.9.3",
							to: "typescript": "^4.3.5",

2.Then: git clone https://github.com/ionic-team/tutorial-photo-gallery-vue 
	I tried both nvm use 12.14.0 and 14.17 

3. At first I ran: npm install.
	I got a buch of wierd errors, I fixed by:
	Changing package.json from: "typescript": "~3.9.3",
							to: "typescript": "^4.3.5",
	npm install capacitor
	npm install -g @ionic/cli@latest native-run cordova-res
	npm install @capacitor/camera @capacitor/storage @capacitor/filesystem
	npm install @ionic/pwa-elements
	npm install

Finally ionic serve worked on localhost - including the selfie - but resulted in a way worse pic. 
BUT
the app could not find camera over the LAN.

**Comment by jcesarmobile** [comment]
try updating to latest version of @ionic/pwa-elements, I think all those issue were handled there
