### ISSUE TITLE
"TypeError: Failed to fetch dynamically imported module": for pwa-camera-modal.entry.js

### ISSUE THREAD

**Issue by AshtonRussell93** [ionic-team/tutorial-photo-gallery-vue#20]
When following along with the tutorial, the ```TakePhoto``` method kept returning "```504 (Outdated Optimize Dep)...: node_modules/.vite/deps/pwa-camera-modal.entry.js```."  
I tried removing and reinstalling the node packages and using different browsers, but I was only able to resolve it with the following:
``` typescript
export default defineConfig({
//... vite.config.ts
  optimizeDeps: {
    exclude: ['@ionic/pwa-elements']
  }
}
```
This seems to be a known issue for Vite projects ([Example found on GitHub](https://github.com/vitejs/vite/issues/12434)) at the moment. Which I wasn't sure to post the issue in https://github.com/ionic-team/starters, but since I was following this tutorial figure to post it here.

**Comment by danh65** [comment]
Same here, following the take photo tutorial and got the same error. Finally found this post and it worked for me too! Thanks for posting!

**Comment by jcesarmobile** [comment]
This has been fixed in latest version of PWA elements
