### ISSUE TITLE
photo not saved to filesystem

### ISSUE THREAD

**Issue by peterennis** [ionic-team/tutorial-photo-gallery-vue#4]
@dotNetkow 

Here:

https://ionicframework.com/docs/vue/your-first-app/3-saving-photos

It says:

`Each time a new photo is taken, it’s now automatically saved to the filesystem.`

Where? Testing on Windows 10 and I do not see it.

Debugging shows this:

![2020-10-07 14_20_46-Window](https://user-images.githubusercontent.com/140737/95389308-7aa39180-08a8-11eb-906f-b5b800aa8e8e.png)

https://github.com/peterennis/ae-gallery/commit/63ef4c5de609fa04846a0c720a89d8bc7dbe420c#diff-e82017290860c60ca00f0a113bd7d2efR52-R53

But no trace of a file anywhere.

I assumed the initial app is a PWA using the camera on the laptop
and later is configured for a mobile device.

Confused 😕

**Comment by a2d** [comment]
Ha! I wondered about that too, but the photo is only stored as a base64 encoded string in the browsers local storage, NOT a file on the filesystem.

**Comment by jcesarmobile** [comment]
Yeah, Capacitor Filesystem plugin, when running on web, it stores the files in IndexedDB as most browsers don't have access to the real Filesystem of the computer.
