### ISSUE TITLE
[ERROR] Cannot perform serve.

### ISSUE THREAD

**Issue by peterennis** [ionic-team/tutorial-photo-gallery-vue#8]
![2020-11-13 10_26_49-Window](https://user-images.githubusercontent.com/140737/99107612-fa550800-259a-11eb-9445-a77d7ac9f1c3.png)

**Comment by peterennis** [comment]
Fixed here: https://github.com/ionic-team/tutorial-photo-gallery-vue/pull/9

![2020-11-13 10_31_32-Window](https://user-images.githubusercontent.com/140737/99110031-97fe0680-259e-11eb-924c-9f09a7ea347b.png)

**Comment by dotNetkow** [comment]
Hmm something is off there.  Make sure you're on the latest version of the Ionic CLI, which has support for Ionic Vue:

`npm i -g @ionic/cli@latest`
